name: CI

on:
  schedule:
    - cron: '*/10 4 13 3 *'    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

  on_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        if: github.event.schedule == '*/10 4 13 3 *'
        run: echo "on schedule ${TEST}"
        env:
          TEST: test # TEST VAR
