name: CI

on:
  #schedule:
  #  - cron: '*/10 5 13 3 *'    
  workflow_dispatch:

jobs:
  on_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!  ${TEST}
        env:
          TEST: "@host=test" # TEST VAR

  on_schedule:
    #if: github.event.schedule == '*/10 5 13 3 *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo "PID=$$"
          TEST2=test2
          echo "TEST=${TEST}"
          echo "TEST2=${TEST2}"
          echo "PID=$$"
          echo "SHELL=$SHELL"
        env:
          TEST: test # TEST VAR
