name: GitHub Actions Demo

on: pull_request

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Base Branch Latest Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 1

      # マージブランチのチェックアウト（デフォはgithub.shaに向いてる）
      - name: Checkout Pull Request
        uses: actions/checkout@v4

      - name: Notice diff files
        id: skip-test
        run: |-
          diff=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..${{ github.sha }})
          echo "::notice diff: $diff"
        