name: GitHub Actions Demo

on: pull_request

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Checkout Pull Request Branch
        uses: actions/checkout@v4

      - name: Find changed files
        id: files
        run: |
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}..${{ github.sha }} -- data | awk '{if(f==""){f=$1}else{f=sprintf("%s %s",f,$1)}}END{printf "files=\"%s\"",f}' >> $GITHUB_OUTPUT
      - name: Print files
        run: for f in "${FILES}"; do n=$(dirname ${f});n=${n%%.md};echo "${n}:${f}"; done
        env:
          FILES: ${{ steps.files.outputs.files }}